using System;
using System.Collections.Generic;
using System.Text;
using ADAuditor.Core;

namespace ADAuditor.Report
{
    public static class HtmlReportWriter
    {
        public static string Build(AuditReport rep)
        {
            var sb = new StringBuilder();
            sb.Append(@"<!DOCTYPE html><html lang=""en""><head><meta charset=""utf-8"">");
            sb.Append("<title>AD Audit - ").Append(Enc(rep.DomainName)).Append("</title>");
            sb.Append("<style>");
            sb.Append(@"
body{background:#050805;color:#33ff66;font-family:Consolas,'Lucida Console',monospace;margin:0;padding:24px;}
h1,h2,h3{color:#33ff66;text-shadow:0 0 6px #1e8f3e;}
a{color:#33ff66;}
.banner{border:1px solid #1e8f3e;padding:12px 16px;margin-bottom:18px;}
.meta{color:#1e8f3e;font-size:13px;}
.scores{display:flex;gap:14px;flex-wrap:wrap;margin:18px 0;}
.score{border:1px solid #1e8f3e;padding:12px 18px;min-width:150px;text-align:center;}
.score .v{font-size:34px;font-weight:bold;}
.s-crit{color:#ff3b30;}.s-high{color:#ff8c00;}.s-med{color:#ffb000;}.s-low{color:#7CFC00;}.s-info{color:#1e8f3e;}
table{border-collapse:collapse;width:100%;margin:10px 0 26px;}
th,td{border:1px solid #13351f;padding:6px 9px;text-align:left;vertical-align:top;font-size:13px;}
th{background:#13351f;}
tr:nth-child(even){background:#0c1a12;}
.tag{padding:1px 7px;border:1px solid;border-radius:3px;font-size:11px;font-weight:bold;}
.det{color:#7fae8f;font-size:12px;}
.det ul{margin:4px 0;padding-left:18px;}
.why{color:#9fd9af;font-size:12px;}
.fix{color:#ffb000;font-size:12px;}
");
            sb.Append("</style></head><body>");

            sb.Append("<div class='banner'><h1>// ACTIVE DIRECTORY SECURITY AUDIT</h1>");
            sb.Append("<div class='meta'>");
            sb.Append("DOMAIN: ").Append(Enc(rep.DomainName)).Append(" &nbsp; FOREST: ").Append(Enc(rep.ForestName)).Append("<br>");
            sb.Append("DN: ").Append(Enc(rep.DomainDn)).Append("<br>");
            sb.Append("DC: ").Append(Enc(rep.DomainController)).Append("<br>");
            sb.Append("FUNCTIONAL LEVEL: domain=").Append(rep.DomainFunctionalLevel)
              .Append(" forest=").Append(rep.ForestFunctionalLevel).Append("<br>");
            sb.Append("GENERATED: ").Append(rep.GeneratedUtc.ToString("yyyy-MM-dd HH:mm:ss")).Append(" UTC");
            sb.Append("</div></div>");

            // score panels
            sb.Append("<div class='scores'>");
            sb.Append(ScorePanel("GLOBAL", rep.GlobalScore()));
            foreach (Category c in Enum.GetValues(typeof(Category)))
                sb.Append(ScorePanel(c.ToString(), rep.Score(c)));
            sb.Append("</div>");

            foreach (Category c in Enum.GetValues(typeof(Category)))
            {
                var list = rep.Findings.FindAll(f => f.Category == c);
                if (list.Count == 0) continue;
                list.Sort((a, b) => b.Severity.CompareTo(a.Severity));
                sb.Append("<h2>").Append(c.ToString()).Append(" &mdash; score ").Append(rep.Score(c)).Append("/100</h2>");
                sb.Append("<table><tr><th>Severity</th><th>ID</th><th>Finding</th><th>Details</th></tr>");
                foreach (var f in list)
                {
                    sb.Append("<tr><td>").Append(SevTag(f.Severity)).Append("</td>");
                    sb.Append("<td>").Append(Enc(f.Id)).Append("</td>");
                    sb.Append("<td><b>").Append(Enc(f.Title)).Append("</b>");
                    if (!string.IsNullOrEmpty(f.Rationale))
                        sb.Append("<div class='why'>").Append(Enc(f.Rationale)).Append("</div>");
                    if (!string.IsNullOrEmpty(f.Recommendation))
                        sb.Append("<div class='fix'>FIX: ").Append(Enc(f.Recommendation)).Append("</div>");
                    sb.Append("</td>");
                    sb.Append("<td class='det'>");
                    if (f.Details.Count > 0)
                    {
                        sb.Append("<ul>");
                        foreach (var d in f.Details) sb.Append("<li>").Append(Enc(d)).Append("</li>");
                        sb.Append("</ul>");
                    }
                    sb.Append("</td></tr>");
                }
                sb.Append("</table>");
            }

            sb.Append("<div class='meta'>Generated by ADAuditor. For authorized security assessment only.</div>");
            sb.Append("</body></html>");
            return sb.ToString();
        }

        private static string ScorePanel(string label, int score)
        {
            string cls = score >= 75 ? "s-crit" : score >= 50 ? "s-high" : score >= 25 ? "s-med" : "s-low";
            return "<div class='score'><div>" + Enc(label) + "</div><div class='v " + cls + "'>" + score + "</div></div>";
        }

        private static string SevTag(Severity s)
        {
            string cls, txt;
            switch (s)
            {
                case Severity.Critical: cls = "s-crit"; txt = "CRITICAL"; break;
                case Severity.High: cls = "s-high"; txt = "HIGH"; break;
                case Severity.Medium: cls = "s-med"; txt = "MEDIUM"; break;
                case Severity.Low: cls = "s-low"; txt = "LOW"; break;
                default: cls = "s-info"; txt = "INFO"; break;
            }
            return "<span class='tag " + cls + "'>" + txt + "</span>";
        }

        private static string Enc(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            return s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");
        }
    }
}
